### ISSUE TITLE
Compatibility with 2.1.2 / composer errors

### ISSUE THREAD

**Issue by cizgidekiadam** [meanbee/magento2-serviceworker#1]
Hi,
I tried to install module via composer but there were some errors. Dump is below.

<pre>Problem 1
    - Installation request for meanbee/magento2-serviceworker ^1.0 -> satisfiable by meanbee/magento2-serviceworker[1.0.0].
    - Conclusion: remove magento/module-backend 100.1.1
    - Conclusion: don't install magento/module-backend 100.1.1
    - meanbee/magento2-serviceworker 1.0.0 requires magento/module-backend ^100.1.2 -> satisfiable by magento/module-backend[100.1.2, 100.1.3].
    - Can only install one of: magento/module-backend[100.1.1, 100.1.2].
    - Can only install one of: magento/module-backend[100.1.1, 100.1.3].
    - Installation request for magento/module-backend (locked at 100.1.1) -> satisfiable by magento/module-backend[100.1.1].</pre>

**Comment by tgerulaitis** [comment]
Hi,

Looks like it doesn't like the backend module version in Magento 2.1.2 (looking at the code, the config module version would conflict as well). The restrictions on the module versions in composer.json are only there really because we haven't tested with Magento versions prior to 2.1.3. The extension doesn't need much from Magento, so it should be compatible with all 2.1.x versions.

I've just tested it in 2.1.2 and submitted a pull request for loosening the version requirements.

**Comment by cizgidekiadam** [comment]
@tgerulaitis 
I used the download way for test it. So skipped the version compatibility.
It is working fine, thanks for commit.
